server:  
  port: ${PORT:9596}
  contextPath: /uaa

spring:  
  application:
    name: auth-server

logging:
  level:
    org.springframework.security: TRACE

#security:
#  user:
#    name: root
#    password: password

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/    