server:  
  port: ${PORT:9595}

spring:  
  application:
    name: odontologia-service

#logging:
#  level:
#    account.api.AccountClient: TRACE

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 5
#    lease-expiration-duration-in-seconds: 5
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
            
      
security:
  oauth2:
    resource:
      #loadBalanced: true
      userInfoUri: http://localhost:9596/uaa/user